import fs from "node:fs";
import path from "node:path";

const NAME=/^[a-z][a-z0-9-]{2,62}$/;
const METHOD=/^(GET|POST|PUT|PATCH|DELETE)$/;

export function validateSpec(spec){
  if(!spec||typeof spec!=="object"||Array.isArray(spec)) throw new Error("spec must be an object");
  if(typeof spec.name!=="string"||!NAME.test(spec.name)) throw new Error("name must match ^[a-z][a-z0-9-]{2,62}$");
  if(typeof spec.version!=="string"||!/^v[0-9]+$/.test(spec.version)) throw new Error("version must look like v1");
  if(!Array.isArray(spec.operations)||spec.operations.length<1||spec.operations.length>100) throw new Error("operations must contain 1..100 items");
  const seen=new Set();
  for(const op of spec.operations){
    if(!op||typeof op!=="object"||!METHOD.test(op.method)||typeof op.path!=="string"||!/^\/[A-Za-z0-9_:\-\/{}]*$/.test(op.path)) throw new Error("invalid operation");
    const key=op.method+" "+op.path;
    if(seen.has(key)) throw new Error("duplicate operation: "+key);
    seen.add(key);
    if(typeof op.summary!=="string"||op.summary.length>300) throw new Error("operation summary is required and <=300 chars");
  }
  return {name:spec.name,version:spec.version,description:typeof spec.description==="string"?spec.description.slice(0,1000):"",auth:spec.auth==="api-key"?"api-key":"none",operations:spec.operations.map(op=>({method:op.method,path:op.path,summary:op.summary}))};
}

function routeSource(op,auth){
  const method=op.method.toLowerCase();
  const route=JSON.stringify(op.path);
  const summary=JSON.stringify(op.summary);
  const body=method==="get"||method==="delete" ? "{ ok:true, api:"+JSON.stringify(op.path)+" }" : "{ ok:true, received:request.body??null }";
  const guard=auth==="api-key" ? "if(!request.headers['x-api-key']) return reply.code(401).send({error:'Unauthorized'});\n  " : "";
  return "app."+method+"("+route+",async(request,reply)=>{\n  "+guard+"return reply.send("+body+");\n}); // "+summary;
}

export function compileApi(spec,outRoot){
  const s=validateSpec(spec);
  const dir=path.join(outRoot,s.name);
  fs.mkdirSync(dir,{recursive:true,mode:0o755});
  const routes=s.operations.map(op=>routeSource(op,s.auth)).join("\n");
  const server="import Fastify from \"fastify\";\nconst app=Fastify({logger:true});\nconst port=Number(process.env.PORT||3000);\napp.get(\"/health\",async()=>({ok:true,service:"+JSON.stringify(s.name)+",version:"+JSON.stringify(s.version)+",factory:\"api-factory\"}));\n"+routes+"\nawait app.listen({port,host:\"0.0.0.0\"});\n";
  const pkg=JSON.stringify({name:s.name,version:"0.1.0",private:true,type:"module",scripts:{start:"node server.mjs"},dependencies:{fastify:"5.6.1"}},null,2)+"\n";
  const openapi={openapi:"3.1.0",info:{title:s.name,version:s.version,description:s.description},paths:{}};
  for(const op of s.operations){const method=op.method.toLowerCase();openapi.paths[op.path]??={};openapi.paths[op.path][method]={summary:op.summary,responses:{"200":{description:"Success"},"401":{description:"Unauthorized"}}};}
  if(s.auth==="api-key") openapi.components={securitySchemes:{ApiKey:{type:"apiKey",in:"header",name:"x-api-key"}}};
  fs.writeFileSync(path.join(dir,"server.mjs"),server);
  fs.writeFileSync(path.join(dir,"package.json"),pkg);
  fs.writeFileSync(path.join(dir,"openapi.json"),JSON.stringify(openapi,null,2)+"\n");
  fs.writeFileSync(path.join(dir,"README.md"),"# "+s.name+"\n\nGenerated by API Factory.\n\nVersion: "+s.version+"\n\n"+s.description+"\n\nAuth: "+s.auth+"\n");
  return {name:s.name,version:s.version,directory:dir,files:["server.mjs","package.json","openapi.json","README.md"],operations:s.operations.length};
}
